management:
  endpoints:
    web:
      exposure:
        include: health,beans,loggers,env,info
  endpoint:
    health:
      show-details: "ALWAYS"
logging:
  level:
    ROOT: INFO
    ##org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
  port: 8090

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

connection:
  service:
    url: http://demo-feign.tst-namespace-default.svc.cluster.local/


